export default [
    {
        id:1,
        name:'文本框',
        img:'../../static/img/add_form_img01.png',
        type:'text'
    },
    {
        id:2,
        name:'下拉框',
        img:'../../static/img/add_form_img05.png',
        type:'select'
    },{
        id:3,
        name:'单选',
        img:'../../static/img/add_form_img03.png',
        type:'radio'
    },{
        id:4,
        name:'多选',
        img:'../../static/img/add_form_img04.png',
        type:'checkbox'
    },{
        id:5,
        name:'多行文本',
        img:'../../static/img/add_form_img02.png',
        type:'text'
    },{
        id:6,
        name:'时间',
        img:'../../static/img/add_form_img06.png',
        type:'date'
    },{
        id:7,
        name:'上传',
        img:'../../static/img/add_form_img07.png',
        type:'file'
    },{
        id:8,
        name:'省市区',
        img:'../../static/img/add_form_img08.png',
        type:'text'
    }
]